/*
 * File: admin/view/CmsViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.view.CmsViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        padding: 5,
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    margins: '5 5 5 5',
                    region: 'north',
                    border: 1,
                    frame: true,
                    height: 69,
                    html: '<div><a href="admin/logout.html">退出</a></div>'
                },
                {
                    xtype: 'container',
                    margins: '5 5 5 5',
                    region: 'south',
                    border: 1,
                    frame: true,
                    height: 20
                }
            ]
        });

        me.callParent(arguments);
    }

});