/*
 * File: admin/view/CommonPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.view.CommonPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.commonPanel',

    layout: {
        type: 'border'
    },
    title: '常规管理',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    collapseMode: 'header',
                    region: 'west',
                    border: 1,
                    frame: true,
                    id: 'commonLeft',
                    padding: 2,
                    width: 120,
                    resizable: false,
                    layout: {
                        type: 'anchor'
                    },
                    collapseDirection: 'left',
                    collapsed: false,
                    collapsible: true,
                    title: '常规管理',
                    titleCollapse: true,
                    items: [
                        {
                            xtype: 'button',
                            anchor: '1',
                            frame: false,
                            itemId: 'runStatusBtn',
                            margin: '2 0',
                            text: '网站运行状态'
                        },
                        {
                            xtype: 'button',
                            anchor: '1',
                            itemId: 'bulletinManageBtn',
                            margin: '2 0',
                            text: '网站公告设置'
                        },
                        {
                            xtype: 'button',
                            anchor: '1',
                            itemId: 'advertisementManageBtn',
                            margin: '2 0',
                            text: '网站广告管理'
                        },
                        {
                            xtype: 'button',
                            anchor: '1',
                            itemId: 'linkManageBtn',
                            margin: '2 0',
                            text: '友情链接管理'
                        },
                        {
                            xtype: 'container',
                            html: '<div>技术支持</div>\r\n<ul>\r\n<li>\r\n   Tel:xxx-xxxxxxxx\r\n       xxx-xxxxxxxx\r\n</li>\r\n<li>\r\n    QQ:xxxxxxxx\r\n       xxxxxxxx\r\n</li>\r\n<li>\r\nE-Mail:xx@xx.com\r\n       xx@xx.com\r\n</li>\r\n</ul>'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    addOrShowTab: function(id, panelClass, panelClassParams) {
                        panelClassParams = panelClassParams || {closable : true};
                        var tab = this.getComponent(id);
                        if (!tab){
                            tab = Ext.create(panelClass, Ext.apply({id : id},
                            panelClassParams)
                            );
                            this.add(tab);
                        }
                        this.setActiveTab(tab);
                        return tab;
                    },
                    region: 'center',
                    itemId: 'commonTabPanel'
                }
            ]
        });

        me.callParent(arguments);
    }

});