/*
 * File: admin/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginForm',

    floating: true,
    height: 165,
    width: 280,
    layout: {
        type: 'auto'
    },
    bodyPadding: 10,
    closable: false,
    title: '登录',
    method: 'post',
    url: 'admin/login.do',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            method: 'post',
            url: 'admin/login.do'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    formBind: false,
                    width: 200,
                    fieldStyle: 'margin-bottom:10px;',
                    name: 'username',
                    tabIndex: 1,
                    fieldLabel: '账号',
                    labelWidth: 40,
                    allowBlank: false,
                    blankText: '账号不能为空!',
                    emptyText: '请输入账号'
                },
                {
                    xtype: 'textfield',
                    formBind: false,
                    width: 200,
                    fieldStyle: 'margin-bottom:10px;',
                    inputType: 'password',
                    name: 'password',
                    tabIndex: 2,
                    fieldLabel: '密码',
                    labelWidth: 40,
                    allowBlank: false,
                    blankText: '密码不能为空!',
                    emptyText: '请输入密码'
                },
                {
                    xtype: 'checkboxfield',
                    formBind: false,
                    maxWidth: 100,
                    name: 'rememberMe',
                    tabIndex: 3,
                    boxLabel: '记住登录状态',
                    inputValue: 'true'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        pack: 'end',
                        type: 'hbox'
                    },
                    items: [
                        {
                            xtype: 'button',
                            formBind: false,
                            id: 'loginBtn',
                            shrinkWrap: 0,
                            width: 50,
                            tabIndex: 4,
                            text: '登录'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});