/*
 * File: admin/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.view.Viewport', {
    extend: 'CMS.view.CmsViewport',
    renderTo: Ext.getBody(),
    requires: [
        'CMS.view.LoginForm',
        'CMS.view.CmsViewport',
        'CMS.view.MainTabPanel',
        'CMS.view.CommonPanel',
        'CMS.view.EmployeeManagePanel',
        'CMS.view.OperationManagePanel',
        'CMS.view.ArticleManagePanel',
        'CMS.view.TemplateManagePanel',
        'CMS.view.ResourceManagePanel',
        'CMS.view.SystemManagePanel'
    ]
});