/*
 * File: admin/controller/Common.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.controller.Common', {
    extend: 'Ext.app.Controller',

    views: [
        'CommonPanel'
    ],

    refs: [
        {
            ref: 'commonPanel',
            selector: 'commonPanel',
            xtype: 'panel'
        }
    ],

    onButtonClick: function(button, e, eOpts) {
        var params = {closable : true};
        switch(button.itemId){
            case 'runStatusBtn' : 
            params.title = '网站运行状态';
            break;
            case 'bulletinManageBtn' : 
            params.title = '网站公告管理';
            break;
            case 'advertisementManageBtn' : 
            params.title = '网站广告管理';
            break;
            case 'linkManageBtn' : 
            params.title = '友情链接管理';
            break;
            default : return;
        }
        this.getCommonPanel().getComponent('commonTabPanel').addOrShowTab(button.itemId, 'Ext.panel.Panel', params);
    },

    init: function(application) {
        this.control({
            "#commonLeft button": {
                click: this.onButtonClick
            }
        });
    }

});
