/*
 * File: admin/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.controller.Main', {
    extend: 'Ext.app.Controller',

    views: [
        'MainTabPanel'
    ],

    refs: [
        {
            ref: 'viewport',
            selector: 'viewport'
        }
    ],

    showMainView: function() {
        //var viewport = Ext.create('CMS.view.CmsViewport');
        mainTabPanel = Ext.create('CMS.view.MainTabPanel', {flex: 1,region : 'center'});
        this.getViewport().add(mainTabPanel);
        mainTabPanel.addOrShowTab('commonPanel', 'CMS.view.CommonPanel', {});
        mainTabPanel.addOrShowTab('operationManagePanel', 'CMS.view.OperationManagePanel', {});
        mainTabPanel.addOrShowTab('articleManagePanel', 'CMS.view.ArticleManagePanel', {});
        mainTabPanel.addOrShowTab('templateManagePanel', 'CMS.view.TemplateManagePanel', {});
        mainTabPanel.addOrShowTab('resourceManagePanel', 'CMS.view.ResourceManagePanel', {});
        mainTabPanel.addOrShowTab('employeeManagePanel', 'CMS.view.EmployeeManagePanel', {});
        mainTabPanel.addOrShowTab('systemManagePanel', 'CMS.view.SystemManagePanel', {});
        mainTabPanel.setActiveTab(0);
    }

});
