/*
 * File: admin/store/Channel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.store.Channel', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'CMS.model.Channel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'CMS.model.Channel',
            storeId: 'channelStore',
            folderSort: true,
            nodeParam: 'parentId',
            root: {
                name: '根栏目'
            },
            proxy: me.processMyAjaxProxy({
                type: 'ajax',
                url: 'admin/channel/tree.json'
            }),
            sorters: {
                property: 'order'
            },
            fields: [
                {
                    name: 'name',
                    type: 'string'
                },
                {
                    name: 'children'
                },
                {
                    name: 'hasArticles'
                },
                {
                    name: 'order',
                    type: 'int'
                },
                {
                    name: 'id',
                    type: 'int'
                }
            ]
        }, cfg)]);
    },

    processMyAjaxProxy: function(config) {
        config.reader = {type:'channelTreeJsonReader'};
        return config;
    }

});