/*
 * File: app/controller/User.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.controller.User', {
    extend: 'Ext.app.Controller',

    models: [
        'User'
    ],
    stores: [
        'Users'
    ],
    views: [
        'UserGrid'
    ],
    refs: [
        {
            ref: 'viewport',
            selector: 'viewport'
        }
    ],

    init: function() {
        this.control({
            "viewport > panel": {
                render: this.onPanelRendered
            },
            "button[id=refresh]": {
                click: this.onRefreshClick
            }
        });

        console.debug('init!');
    },

    onPanelRendered: function(abstractcomponent, options) {
        alert('Hello world!');
    },

    onRefreshClick: function(button, e, options) {
        this.getUsersStore().load();
    },

    showView: function() {
        mainView = Ext.create('MyApp.view.UserGrid', {flex: 1});
        center_container = this.getViewport().down('container[region=center]'); 
        center_container.add(mainView);
        // load the store
        this.getUsersStore().load();
    }

});