/*
 * File: app/view/CategoryComboBox.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CategoryComboBox', {
    extend: 'Ext.form.field.ComboBox',

    name: 'category.id',
    fieldLabel: '类别',
    displayField: 'name',
    hiddenName: 'category.id',
    multiSelect: false,
    store: 'Category',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                beforequery: {
                    fn: me.onComboboxBeforeQuery,
                    scope: me
                }
            }
        });

        me.callParent(arguments);
    },

    onComboboxBeforeQuery: function(queryEvent, options) {
        //this.store.filter('user.id', window.credential.id, true, false);
    }

});