/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginForm',

    draggable: true,
    floating: true,
    height: 125,
    width: 314,
    bodyPadding: 10,
    title: '登陆',
    url: 'login',

    initComponent: function() {
        var me = this;

        me.initialConfig = Ext.apply({
            url: 'login'
        }, me.initialConfig);

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    width: 382,
                    name: 'username',
                    fieldLabel: '账 号',
                    labelWidth: 40,
                    allowBlank: false
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    inputType: 'password',
                    name: 'password',
                    fieldLabel: '密 码',
                    labelWidth: 40
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            id: 'login',
                            text: '登录'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});