/*
 * File: app/view/MainTabPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mainTabPanel',

    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    title: '欢迎'
                }
            ]
        });

        me.callParent(arguments);
    },

    addOrShowTab: function(id, panelClass, panelClassParams) {
        panelClassParams = panelClassParams || {closable : true};
        var tab = this.getComponent(id);
        if (!tab){
            tab = Ext.create(panelClass, Ext.apply({id : id},
            panelClassParams)
            );
            this.add(tab);
        }
        this.setActiveTab(tab);
        return tab;
    }

});