/*
 * File: app/view/NavPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.NavPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.navPanel',

    height: 266,
    autoScroll: true,
    layout: {
        type: 'accordion'
    },
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    html: '<ul>\r\n    <li id="charge_list"><a>账单列表</a></li>\r\n    <li id="charge_list"><a href="#">账单</a></li>\r\n</ul>',
                    collapsed: false,
                    title: '账单管理'
                },
                {
                    xtype: 'panel',
                    collapsed: true,
                    title: '账号管理'
                }
            ]
        });

        me.callParent(arguments);
    }

});