/*
 * File: app/model/Charge.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Charge', {
    extend: 'Ext.data.Model',

    uses: [
        'MyApp.model.Category'
    ],

    idProperty: 'id',

    fields: [
        {
            name: 'amount',
            mapping: 'amount',
            type: 'float'
        },
        {
            name: 'date',
            dateFormat: 'Y-m-d H:i:s',
            mapping: 'date',
            type: 'date'
        },
        {
            name: 'remark',
            mapping: 'remark'
        },
        {
            name: 'id',
            mapping: 'id',
            type: 'int'
        }
    ],

    hasMany: {
        model: 'MyApp.model.Category',
        name: 'categories'
    }
});