/*
 * File: app/controller/Login.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Login', {
    extend: 'Ext.app.Controller',

    views: [
        'LoginForm'
    ],

    refs: [
        {
            ref: 'loginForm',
            selector: 'loginForm'
        }
    ],

    onLoginClick: function(button, e, options) {
        this.login();
    },

    onSpecialKey: function(field, e) {
        if(e.getKey() == e.ENTER) { 
            this.login();
        }
    },

    init: function(application) {
        this.control({
            "button[id=login]": {
                click: this.onLoginClick
            },
            "textfield": {
                specialkey: this.onSpecialKey
            }
        });
    },

    login: function() {
        var loginForm = this.getLoginForm();
        var form = loginForm.getForm();
        var main = this.getController('MyApp.controller.Main');
        if (form.isValid()) {
            form.submit({
                success: function(form, action) {
                    Ext.Msg.alert('Success', action.result.msg);
                    loginForm.hide();
                    main.showMainView();
                },
                failure: function(form, action) {
                    Ext.Msg.alert('Failed', action.result.msg);
                }
            });
        }
    }

});
