/*
 * File: app/store/Charge.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Charge', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Charge'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'MyStore',
            model: 'MyApp.model.Charge',
            proxy: {
                type: 'ajax',
                api: {
                    read: 'charge/list.json',
                    create: 'charge/save',
                    update: 'charge/{id}',
                    destroy: 'charge/{id}'
                },
                url: 'charge/list.json'
            },
            fields: [
                {
                    name: 'id',
                    mapping: 'id',
                    type: 'int'
                },
                {
                    name: 'amount',
                    mapping: 'amount',
                    type: 'float'
                },
                {
                    name: 'date',
                    mapping: 'date',
                    type: 'date'
                },
                {
                    name: 'remark',
                    mapping: 'remark'
                },
                {
                    name: 'userId',
                    mapping: 'userId',
                    type: 'int'
                }
            ]
        }, cfg)]);
    }
});