/*
 * File: app/view/ui/UserGrid.js
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Designer does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.UserGrid', {
    extend: 'Ext.grid.Panel',

    title: 'My Grid Panel',
    store: 'Users',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    id: 'id',
                    dataIndex: 'id',
                    text: 'id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'name'
                },
                {
                    xtype: 'numbercolumn',
                    id: 'age',
                    dataIndex: 'age',
                    text: 'age',
                    format: '0'
                },
                {
                    xtype: 'datecolumn',
                    id: 'birth',
                    dataIndex: 'birth',
                    text: 'birth',
                    format: 'Y-m-d'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'sex',
                    text: 'sex'
                }
            ],
            viewConfig: {

            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'button',
                            id: 'refresh',
                            text: 'Refresh'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});