/*
 * File: admin/model/Channel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CMS.model.Channel', {
    extend: 'Ext.data.Model',
    alias: 'model.channel',

    idProperty: 'id',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'name',
            type: 'string'
        },
        {
            name: 'alias',
            type: 'string'
        },
        {
            name: 'order',
            type: 'int'
        },
        {
            name: 'icon',
            type: 'string'
        },
        {
            name: 'description',
            type: 'string'
        },
        {
            name: 'channelTpl',
            type: 'string'
        },
        {
            name: 'articleTpl',
            type: 'string'
        },
        {
            name: 'status',
            type: 'string'
        },
        {
            name: 'creatorName',
            type: 'string'
        }
    ]
});