/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'User',
        'Category'
    ],
    stores: [
        'Category'
    ],
    views: [
        'LoginForm',
        'MainTabPanel',
        'ChargeEditForm'
    ],
    autoCreateViewport: true,
    name: 'MyApp',
    controllers: [
        'Login',
        'Main',
        'Nav',
        'Charge'
    ],

    launch: function() {
        Ext.QuickTips.init();
        Ext.getBody().on("contextmenu", Ext.emptyFn, null, {preventDefault: true}); 
        Ext.MessageBox.msgButtons.ok.text = Ext.MessageBox.buttonText.ok = '确定';
        Ext.MessageBox.msgButtons.cancel.text = Ext.MessageBox.buttonText.cancel = '取消';
        Ext.MessageBox.msgButtons.yes.text = Ext.MessageBox.buttonText.yes = '是';
        Ext.MessageBox.msgButtons.no.text = Ext.MessageBox.buttonText.no = '否';

        loginForm = Ext.create('MyApp.view.LoginForm', {}).show();
        //this.getController('MyApp.controller.Main').showMainView();
    }

});
